jobs:
  container-test-job:
    container:
      image: cfidentity/uaa-${{ matrix.database }}
      options: --privileged --tty --interactive --shm-size=1G
      volumes:
      - ${{ github.workspace }}:/root/uaa
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set env
      run: echo "DB=$(echo ${{ matrix.database }} | sed 's/[-0-9]//g')" >> $GITHUB_ENV
    - continue-on-error: true
      name: Check out repository code
      uses: actions/checkout@v4
    - continue-on-error: true
      id: testrun
      name: JUnit tests on container
      run: /root/uaa/scripts/unit-tests.sh $DB,default
    - continue-on-error: true
      if: steps.testrun.outcome == 'failure'
      name: Test result upload
      uses: actions/upload-artifact@v4
      with:
        name: Server test
        path: /root/uaa/*/build/reports/tests/test/
    - continue-on-error: true
      if: steps.testrun.outcome == 'failure'
      name: Check error Result
      run: exit 1
    strategy:
      fail-fast: false
      matrix:
        database:
        - postgresql-11
        - postgresql-15
        - mysql
        - mysql-8
name: JUnit tests on database
on:
  repository_dispatch:
    types: trigger-ga___unit-tests.yml
permissions:
  pull-requests: read
